# .gitlab-ci.yml

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip/
    - venv/

.test_template: &test_template
  stage: test
  image: python:$PYTHON_VERSION
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - python -m pip install --upgrade pip
    - pip install black flake8 mypy pytest
    - pip install -e ".[dev]"
    - pip install types-requests pandas-stubs types-PyYAML types-networkx
    - pip install -r requirements.txt || echo "No requirements.txt found"
  script:
    # Lint checks
    - black . --line-length 79 --check
    - flake8 .
    - mypy pipetrack --exclude 'pipetrack/api/main.py'
    # Run tests with coverage
    - pytest --maxfail=1 --disable-warnings -q tests/
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:python3.9:
  <<: *test_template
  variables:
    PYTHON_VERSION: "3.9"

test:python3.10:
  <<: *test_template
  variables:
    PYTHON_VERSION: "3.10"

test:python3.11:
  <<: *test_template
  variables:
    PYTHON_VERSION: "3.11"

test:python3.12:
  <<: *test_template
  variables:
    PYTHON_VERSION: "3.12"
