version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP=host.docker.internal:9092
    volumes:
      - .:/app:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
